### ISSUE TITLE
App crash when clicking the eye symbol

### ISSUE THREAD

**Issue by daMatz** [artnc/chronofile#2]
Hey! I am currently not at the notebook, therefore no logcat debug output, but when clicking the eye symbol without having tracked anything, the app crashed.

I'm on Android 10

**Comment by duhow** [comment]
+1 with release v1.0.1

**Comment by duhow** [comment]
https://hastebin.com/fajigajoru

**Comment by Heusini** [comment]
this only happens if there are no entries at all in the app

**Comment by artnc** [comment]
Fixed in 1.0.2!

https://github.com/artnc/chronofile/releases
