### ISSUE TITLE
Config file documentation 

### ISSUE THREAD

**Issue by JoeKlemmer** [artnc/chronofile#3]
It would be helpful if there was some documentation on the config file. Either comments in the file or something on the GitHub page that explains what options and/or setting exist.

**Comment by artnc** [comment]
Only one `activityGroups` option is supported at the moment. Would this make sense?

![Screenshot_1640849169](https://user-images.githubusercontent.com/2595572/147730508-44dc5c26-d86f-4425-bce8-9c3bc52b879e.png)

**Comment by artnc** [comment]
Released in 1.0.2!

https://github.com/artnc/chronofile/releases

**Comment by JoeKlemmer** [comment]
That seems fine.  At some point, it might be worthwhile to look into
managing the config in a more "user friendly" method than JSON.


*-- Info - https://joeklemmer.com <https://joeklemmer.com>*

**Comment by artnc** [comment]
Yeah, it's JSON mainly just because it's easy and I've been the only user

**Comment by artnc** [comment]
(Also happy to accept PRs from anyone for this!)
